
all: three.min.js dat.gui.min.js stats.min.js Lut.js OrbitControls.js TransformControls.js

three.min.js: ~/repos/mrdoob/three.js/build/three.min.js
	cp $< $@

dat.gui.min.js: ~/repos/mrdoob/three.js/examples/js/libs/dat.gui.min.js
	cp $< $@

stats.min.js: ~/repos/mrdoob/three.js/examples/js/libs/stats.min.js
	cp $< $@

OrbitControls.js: ~/repos/mrdoob/three.js/examples/js/controls/OrbitControls.js
	cp $< $@

TransformControls.js: ~/repos/mrdoob/three.js/examples/js/controls/TransformControls.js
	cp $< $@

Lut.js: ~/repos/mrdoob/three.js/examples/js/math/Lut.js
	cp $< $@
